### ISSUE TITLE
avoid global variables whenever possible

### ISSUE THREAD

**Issue by pelikhan** [alankrantas/pxt-DHT11_DHT22#4]
https://github.com/alankrantas/pxt-DHT11_DHT22/blob/a12cc04de5703c28fbbd13636c37d4dae154b9b3/dht11_dht22.ts#L8

**Comment by alankrantas** [comment]
I'm afraid I have to keep that; each query took almost 30 ms, and I don't want people to query twice for both temperature and humidity data.
