### ISSUE TITLE
Random freezing/locking up of code 

### ISSUE THREAD

**Issue by evandevon** [alankrantas/pxt-DHT11_DHT22#5]
Thanks for the extension!
The extension seems to work totally fine and then at random times totally freezes/locks up the Micro:Bit, requiring a restart. Problem happens anywhere from a few minutes to a few hours of runtime. All other DHT sensor Micro:Bit extensions I've tested seem to have the same issue.
- Everything is sitting still on a desk with no physical disconnections (I have some code checking for that before querying/responding checking)
- Querying once per minute (with a delayed start, like in the instructions)
- Micro:Bit is running off USB from computer with no other indications of power issues (sensor is running off the 3.3v output which I understand is at the low end of its power requirements)
- Tested with different DHT11 and DHT22 sensors with same problem
- Tested with different micro:bits with same problem

I'd like to use micro:bits over multiple days in multiple locations, transmitting DHT11 or 22 temperature and humidity data via radio 'back to base', and so am looking for reliable ways to access the sensor data.  

According to this thread (https://arduino.stackexchange.com/questions/52431/dht22-hanging-up-entire-program) there is an issue with 
the way adafruit implements their library, leading to lock ups, which does not happen with this library https://github.com/markruys/arduino-DHT
Is there a chance that your implementation (as well as the others) has similar issues?

Cheers,
Ev

**Comment by alankrantas** [comment]
I'll test it later when I have time. But I suspect this is mostly the DHTs' issue.

For triggering the DHTs to output data, the controller board has to give a specific sequence of signals to the DHTs, then wait for the sensor to return a specific sequence of signals. Then the sensor will return 40 bits in a similar manner (2 bytes for humidity, 2 bytes for temperature and 1 byte as the checksum). Even if all 40 bytes are received, the checksum may still fail. And the transmit process may very well fail halfway, causing the board hanging for the next bit that will never come.

The bit-reading process would be easily affected (and thus freezed) by various factors, including the CPU clock speeed and built-in watchdog/pin interrupts, etc. Frankly, now I don't think DHTs are practical weather sensors, and I don't have the no knowledge to fix this.

In theory I can try to write a version that can bail the protocol whenever the sensor stopped responding (which may not work well on micro:bit V1 for the slower clock speed), or a version that simply reads and do no bother to wait for the signal changes (which is how https://github.com/markruys/arduino-DHT does it, but I don't think you can replicate something works in C++ to a different language/board ecosystem). Both of which I don't have time to work on now. I think the more practical and quicker solution is to use sensors like BMP180 or BME280 (both are using I2C protocol and are pretty reliable in my experiences).

**Comment by evandevon** [comment]
Thanks for the fast and detailed reponse!
That's a pity about the DHT sensors, as I have access to a bunch of them. The BME280 looks to be the way to go for what I need, I'll order one and test it out for reliability. 

Thanks again!
Ev
